### ISSUE TITLE
travis ci build fails due to entrypoint.sh permisions

### ISSUE THREAD

**Issue by nik-rimor** [testdrivenio/testdriven-app-2.3#26]
Hi , 
It seems Travis CI build (when push to GitHub) fails always with the same error:
```
Creating flask-docker-react_users-db_1 ... 
ERROR: for flask-docker-react_users_1  Cannot start service users: oci runtime error: container_linux.go:265: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": permission denied"
ERROR: for users  Cannot start service users: oci runtime error: container_linux.go:265: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": permission denied"
ERROR: Encountered errors while bringing up the project.
The command "docker-compose -f docker-compose-dev.yml up --build -d" failed and exited with 1 during .
Your build has been stopped.
```
I have successfully followed the course until the travis CI point.  I can run it locally or on AmazonEC2 but the same build fails on Travis CI.

I am using Windows 10 Pro and latest release of Docker for Windows as of November 2018.
My docker-compose version is 1.23.2

When i check the permissions of the entrypoint.sh file from commander cmd i get 

-rwxr-xr-x 1 nikos 197121  155 Dec 28 16:44 entrypoint.sh*

my **docker-dev file** is:
```
# base image
FROM python:3.6.5-alpine

# install dependencies
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add emtrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

# add app
COPY . /usr/src/app
RUN chmod +x /usr/src/app/entrypoint.sh

# run server
CMD ["/usr/src/app/entrypoint.sh"]
```

and my **docker-compose-dev** 
```
version: '3.6'

services: 

  users:
    build: 
      context: ./services/users
      dockerfile: Dockerfile-dev
    volumes: 
      - './services/users:/usr/src/app'
    ports: 
      - 5001:5000
    environment: 
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig 
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on: 
      - users-db  

  users-db:
    build: 
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports: 
      - 5435:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 8081:80
    depends_on:
      - users
```
